---
output: 
  html_document:
    css: styles.css
    toc: true
    

runtime: shiny 


---

```{css, echo=FALSE}
    body .main-container {
      max-width: 100% !important;
      width: 90% !important;
    }
    body {
      max-width: 90% !important;
    }
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE )

library(simmer)
library(tidyverse)
library(shiny)
library(truncnorm)
library(shiny)
library(reactable)
library(patchwork)
library(rhandsontable)
library(scales)
library(ggforce)
library(here)
library(waiter)
library(shinydashboardPlus)
library(ggrepel)
library(slider)
library(memoise)
library(gtree)

source("R/create_enums.R", encoding = "UTF-8")
source("R/game_simulation.R", encoding = "UTF-8")
source("R/simmer.R", encoding = "UTF-8")
source("R/game_solver.R", encoding = "UTF-8")



local_cache <- cachem::cache_disk("data", max_size = Inf )



simulate_core <- function(input, n_executions_game, solve_game = FALSE, run_parallel = TRUE, use_memo = TRUE){
  

  possible_strategy_dev <- tibble(
    strategy_dev = c(actions$Diligent, actions$Kludgy )
  )
  
  possible_strategy_rev <- tibble(
    strategy_rev = c(actions$Careful, actions$Negligent  )
  )
  
  possible_strategy_meta <- tibble(
    strategy_meta = c(actions$Accurate, actions$Inaccurate  )
  )

  #retirar
  possible_devs <- crossing(
    possible_strategy_dev,
    possible_strategy_rev,
    possible_strategy_meta
  ) %>% 
    mutate(
      p_dev = row_number()
    ) 
    
  unique_games <- expand.grid(1:8, 1:8, 1:8) %>% 
    rename(
      dev_1 = 1,
      dev_2 = 2,
      dev_3 = 3
    ) %>% 
    mutate(
      id = row_number()
    ) %>%  
    pivot_longer(
      cols = -id,
      values_to = "strategy",
      names_to = "dev"
    ) %>% 
    group_by(
      id, strategy
    ) %>% 
    summarise(
      n = n()
    ) %>% 
    pivot_wider(
      names_from = strategy,
      values_from = n,
      values_fill = 0
    ) %>% 
    group_by(
      across(
        .cols = matches("[0-9]"),
      )
    ) %>% 
    nest() %>% 
    ungroup() %>% 
    mutate(
      id_unique = row_number()
    ) %>% 
    unnest(data) %>% 
    select(id, id_unique)

  
  first_games <- unique_games %>% 
    arrange(
      id_unique,
      id
    ) %>% 
    group_by(
      id_unique  
    ) %>% 
    slice_head(
      n = 1
    ) 
    

  games <- expand.grid(1:8, 1:8, 1:8) %>% 
    rename(
      dev_1 = 1,
      dev_2 = 2,
      dev_3 = 3
    ) %>% 
    mutate(
      game = row_number()
    ) %>% 
    pivot_longer(
      cols = -game,
      names_to = "dev",
      values_to = "p_dev"
    ) %>% 
    left_join(
      possible_devs,
      by = "p_dev"
    ) %>% 
    #retirar
    #MEXER
    # filter(
    #   dev == "dev_1" & strategy_dev == "Kludgy" & strategy_rev == "Careful" & strategy_meta == "Accurate" |
    #   dev == "dev_2" & strategy_dev == "Diligent" & strategy_rev == "Negligent" & strategy_meta == "Accurate" |
    #   dev == "dev_3" & strategy_dev == "Diligent" & strategy_rev == "Careful" & strategy_meta == "Inaccurate"
    # ) %>%
    # group_by(
    #   game
    # ) %>%
    # filter(
    #   n() == 3
    # ) %>%
    ungroup()

  

  info <- list()
    
  values <- map(
    .x = names(input),
    .f = ~{
      if(.x %in% c("devs_1", "devs_2")){
        info[[.x]] <- hot_to_r(input[[.x]])
      }else{
        info[[.x]] <- input[[.x]]   
      }
      
    }
  )

  names(values) <- names(input)

  values_game <- values[str_detect(string = names(values), pattern = "_game$")]
  names_game <- names(values_game) %>% str_remove(pattern = "_game$")
  names(values_game) <- names_game
  
  

  
  simulate_and_label <- function(round, values, use_memo = TRUE, debug = FALSE){

    if(use_memo){
      simulated <- simulate_game_simmer_memo(values, round, debug = debug)  
    }else{
      simulated <- simulate_game_simmer(values, round, debug = debug)  
    }

    simulated
  
  }
  
  
  summarise_executions_to_payoff <- function(results, by_execution = TRUE){
  

    stages <- tibble::tribble(
      ~id, ~name, ~phase,
      1,  "Development", "Start",
      2,  "Development", "End",
      3,  "Review", "Start",
      4,  "Review", "End",
      5,  "MetaReview", "Start",
      6,  "MetaReview", "End",
      7,  "Merge", "Start",
      8,  "Merge", "End",
    )


    
    data <- results %>%
    mutate(
      pullrequest = str_extract(string = key, pattern = "pr[0-9]*"),
      field = str_extract(string = key, pattern = "(?:_).*") %>% str_remove("_"),
      .before = value
    ) %>%
    select(-key) %>% 
    tidyr::pivot_wider(
      names_from = field,
      values_from = value
    ) %>% 
    dplyr::arrange(time) %>%
    dplyr::group_by(pullrequest, combination, execution) %>%
    tidyr::fill(
      dplyr::everything(),
      .direction = "down"
    ) %>% 
    dplyr::ungroup() %>%
    dplyr::left_join(
      stages %>% dplyr::rename(cur_stage = name),
      by = c("stage" = "id")
    ) %>% 
    dplyr::mutate(
      dplyr::across(
        .cols = where(is.numeric) & !time,
        .fns = as.integer
      )
    )
    

    output <- data %>%   
      filter(
        cur_stage == "Merge",
        phase == "End"
      ) %>%
      group_by(
        combination,
        execution,
        developer
      ) %>%
      summarise(
        merges = n()
      ) 
      
      
      if(!by_execution){
        output <- output
          group_by(
            developer,
            combination
          ) %>%
          summarise(
            merges = mean(merges)
          )
      }
    
    output 
  
  
  }
  
  simulate_executions <- function(values, n_executions, combination, return_results = FALSE, use_memo = TRUE, debug = FALSE){
  

    result <- map(
      .x = 1:n_executions,
      .f = ~simulate_and_label(
        round = .x,
        values = values,
        use_memo = use_memo
      )
    )
  

    if(return_results){   
      if(debug){
        final_result <- map2_df(
          .x = result,
          .y = 1:length(result),
          .f = ~{.x$data %>%
              mutate(
                combination = combination,
                execution = .y
              )}
        )
      }else{
        final_result <- map2_df(
          .x = result,
          .y = 1:length(result),
          .f = ~{.x %>%
              mutate(
                combination = combination,
                execution = .y
              )}
        )
      }
      
      final_result
    }else{
      tibble(teste = 1)
    }
  
    
  }

  
  
  create_game <- function(this_game, values){
    

      saida <- values

            
      developers <- games %>% 
        filter(
          game == this_game
        ) %>% 
        dplyr::select(
          strategy_dev,
          strategy_rev,
          strategy_meta
        )
      
      #mexer
      #browser()
      saida$total_steps <- 550
      # saida$prob_review = 1
      # saida$prob_meta_review = 1
      # saida$entropy_factor =  1.1
      
      saida$devs <- developers
      

      saida 
    }  

  

  
  
  values_game <- map(
    .x = min(games$game):max(games$game),
    .f = ~create_game(this_game = .x, values = values_game)
  )



  values_game_firsts <- values_game %>% 
    enframe() %>% 
    filter(
      name %in% first_games$id
    )
  
  values_game_all <- values_game
  
  values_game <- values_game_firsts$value
  

  #MEXER
  # values_game <- values_game[sample(x = 1:length(values_game), size = 1)]

  n_game <- n_executions_game


  tictoc::tic("simulate")
  

  if(run_parallel){

    results_game <- furrr::future_map2_dfr(
      .x = values_game,
      .y = first_games$id,
      .f = ~simulate_executions(
        values = .x, 
        n_executions = n_game, 
        combination = .y, 
        return_results = solve_game, 
        use_memo = use_memo  ),
      progress = TRUE,
      .options = furrr::furrr_options(seed = 222 )
    ) 
      
    tictoc::toc()
    
    
    results_game <- results_game %>% 
      summarise_executions_to_payoff()
    
    
  }else{
    

    tictoc::tic("solve")
    
    results_game <- purrr::map2_dfr(
      .x = values_game,
      .y = 1:length(values_game),
      .f = ~simulate_executions(
        values = .x, 
        n_executions = n_game, 
        combination = .y, 
        return_results = solve_game ,
        use_memo = use_memo
      ) 
    ) %>%  
      summarise_executions_to_payoff()
    
    tictoc::toc()




  }
  
  
  


  results_game_final <- results_game %>% 
    inner_join(
      first_games %>%  rename(id_run = id),
      by = c("combination" = "id_run")
    ) %>% 
    inner_join(
      unique_games %>%  rename(id_receive = id),
      by = c("id_unique")
    ) %>% 
    select(
      combination = id_receive,
      execution,
      developer,
      merges
    )
  


  
  #solve

  if(solve_game){
    
    eqs_game <- solve_game(params = values_game_all, results = results_game_final)

    saida <- eqs_game
    
  }else{
    saida = 0
  }

  saida

  
}




simulate_game_simmer_memo <- memoise(simulate_game_simmer, cache = local_cache  )

simulate_core_memo <- memoise(simulate_core, cache = local_cache)

# simulate_game_simmer_memo <- simulate_game_simmer


# # future::plan(future::multicore)
# 
future::plan(strategy = future::multisession)

likert_harm <- tibble(
  entropy = c(1, 1.025, 1.05, 1.075, 1.1),  
  description = c("No", "A little", "Moderately", "Much", "A great deal")
)
  



```




# Simulation
 
  
  

```{r, echo=FALSE}
#user inputs


n_executions_1 <- reactive({
  
  input$n_executions_1
  
})


n_executions_2 <- reactive({
  
  input$n_executions_2
  
})



splitLayout(

  wellPanel( 

    style = "background:#66bbff",
  

    "Parametrization 1" %>%  h3(),

      
    "Players" %>%  h4(),
    
    wellPanel(
      
      
    
    splitLayout(cellWidths = c("50%", "50%"),
    
    verticalLayout(  
    "Developers" %>% h5(),
      rHandsontableOutput("devs_1", width = 400, height = 250)  
    )
    
    )
    
    ),
    
    
    splitLayout(
    
    verticalLayout(  
    "Development Process" %>%  h4(),
    
    wellPanel(
    
      sliderInput("process_fraction_review_1",label="% of pull requests reviewed", min = 0, max = 100, post  = " %", value = 50, step = 5),
      
      sliderInput("process_fraction_metareview_1",label="% of reviews metareviewed", min = 0, max = 100, post  = " %", value = 50, step = 5)
    
        
    
    )
    )
    ,
    
    verticalLayout(  
    "Development" %>%  h4(),
    
    
    wellPanel(
    
      radioButtons(
        inputId = "characteristics_kludges_harmful_1",
        label = "Kludges harmful",
        choices = likert_harm$description
      )
      
    
    )
    
    )
    
    )
  
  )
    
    
  ,


  wellPanel( 
    
    
    style = "background:#aaddaa",
  

    "Parametrization 2" %>%  h3(),
    
          
    "Players" %>%  h4(),
    
    wellPanel(
      
      
    
    splitLayout(cellWidths = c("50%", "50%"),
    
    verticalLayout(  
    "Developers" %>% h5(),
      rHandsontableOutput("devs_2", width = 400, height = 250)  
    )
    
    )
    
    ),
    
    
    splitLayout(
    
    verticalLayout(  
    "Development Process" %>%  h4(),
    
    wellPanel(
    
      sliderInput("process_fraction_review_2",label="% of pull requests reviewed", min = 0, max = 100, post  = " %", value = 50, step = 5),
      
      sliderInput("process_fraction_metareview_2",label="% of reviews metareviewed", min = 0, max = 100, post  = " %", value = 50, step = 5)
    
        
    
    )
    )
    ,
    
    verticalLayout(  
    "Development" %>%  h4(),
    
    
    wellPanel(
    
      radioButtons(
        inputId = "characteristics_kludges_harmful_2",
        label = "Kludges harmful",
        choices = likert_harm$description
      )
      
    
    )
    
    )
    
    )
  
  )
    


    
)
output$devs_1 <- renderRHandsontable({

    DF = tibble(
      strategy_dev = c(actions$Diligent, actions$Diligent, actions$Diligent),
      strategy_rev = c(actions$Careful, actions$Careful, actions$Careful ),
      strategy_meta = c(actions$Accurate, actions$Accurate, actions$Accurate )
    )

    rhandsontable(DF, width = 400) %>%
        hot_col(
          col = "strategy_dev",
          type = "dropdown",
          source = c(actions$Diligent, actions$Kludgy)  
        ) %>% 
        hot_col(
          col = "strategy_rev",
          type = "dropdown",
          source = c(actions$Careful, actions$Negligent)  
        ) %>% 
        hot_col(
          col = "strategy_meta",
          type = "dropdown",
          source = c(actions$Accurate, actions$Inaccurate)  
        ) 

  })




output$devs_2 <- renderRHandsontable({

    DF = tibble(
      strategy_dev = c(actions$Diligent, actions$Diligent, actions$Diligent),
      strategy_rev = c(actions$Careful, actions$Careful, actions$Careful ),
      strategy_meta = c(actions$Accurate, actions$Accurate, actions$Accurate )
    )

    rhandsontable(DF, width = 400) %>%
        hot_col(
          col = "strategy_dev",
          type = "dropdown",
          source = c(actions$Diligent, actions$Kludgy)  
        ) %>% 
        hot_col(
          col = "strategy_rev",
          type = "dropdown",
          source = c(actions$Careful, actions$Negligent)  
        ) %>% 
        hot_col(
          col = "strategy_meta",
          type = "dropdown",
          source = c(actions$Accurate, actions$Inaccurate)  
        ) 

  })



```

<br>

<details>
  <summary>Click if you want to see details</summary>


```{r, echo=FALSE}


splitLayout(



  wellPanel(
    
    
  style = "background:#66bbff",


  "Parametrization 1" %>%  h3(),
    
  
  "Game" %>%  h4(),
  
  
  inputPanel(
    fluidPage(
        numericInput(
          inputId = "total_steps_1",
          label = "$$Steps$$" %>% withMathJax(),
          value = "2000",
          step = 1
        ), 
        
        numericInput(
          inputId = "entropy_factor_1",
          label = "$$H$$" %>% withMathJax(),
          value = "1.02",
          step = 0.01
        ) ,
  
        numericInput(
          inputId = "prob_review_1",
          label = "$$P(Review)$$" %>% withMathJax(),
          value = "0.5"
        ) ,
        
        numericInput(
          inputId = "prob_meta_review_1",
          label = "$$P(MetaReview|Review)$$"  %>% withMathJax(),
          value = "0.5"
        ) ,
        
        numericInput(
          inputId = "lambda_1",
          label = "$$\\lambda$$"  %>% withMathJax(),
          value = "1"
        ) ,
        
        numericInput(
          inputId = "n_executions_1",
          label = "$$executions$$"  %>% withMathJax(),
          value = "5"
        ) 
    )
      
  ),
  
  "Development Stage"  %>% h4(),
  
  "(D = Diligent, K = Kludge/Kludgy, R = Reworking)" %>% HTML(),
  
  inputPanel(

    fluidPage(    

        numericInput(
          inputId = "prob_diligent_1",
          label = "$$P(K)|D$$" %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
        numericInput(
          inputId = "prob_kludgy_1",
          label = "$$P(K)|K$$" %>%  withMathJax(),
          value = "0.9",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "mean_time_diligent_1",
          label = withMathJax("$$\\mu|(D, !R)$$"),
          value = "10",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "mean_time_kludgy_1",
          label = withMathJax("$$\\mu|(K, !R)$$"),
          value = "6",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "sd_time_develop_1",
          label = withMathJax("$$\\sigma|(!R)$$"),
          value = "2",
          step = "1"
        ) ,
  
        numericInput(
          inputId = "mean_time_rework_1",
          label = withMathJax("$$\\mu|R$$"),
          value = "3",
          step = "1"
        ) ,
  
        numericInput(
          inputId = "sd_time_rework_1",
          label = withMathJax("$$\\sigma|R$$"),
          value = "5",
          step = "1"
        ) 
    )
  
  ),
  
  
  "Review Stage"  %>% h4(),
  
  "(K = Kludge, C = Careful, N = Negligent)" %>% HTML(),
  
  inputPanel(
    
    fluidPage(
        
        numericInput(
          inputId = "mean_time_review_1",
          label = "$$\\mu$$",
          value = "1",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "sd_time_review_1",
          label = "$$\\sigma$$",
          value = "0.2",
          step = "1"
        ) ,
      
        
        numericInput(
          inputId = "prob_kludgy_review_when_kludge_careful_1",
          label = "$$P(K)|(K, C)$$" %>% withMathJax() ,
          value = "0.85"
        ) ,
      
        numericInput(
          inputId = "prob_kludgy_review_when_not_kludge_careful_1",
          label = "$$P(K)|(!K, C)$$" %>% withMathJax(),
          value = "0.1"
        ) ,
          
        numericInput(
          inputId = "prob_kludgy_review_when_kludge_negligent_1",
          label = "$$P(K)|(K, N)$$" %>% withMathJax(),
          value = "0.25"
        ) ,
      
        numericInput(
          inputId = "prob_kludgy_review_when_not_kludge_negligent_1",
          label = "$$P(K)|(!K, N)$$" %>% withMathJax(),
          value = "0.1"
        ) 
        
    )
  ),
        
  "Metareview Stage"  %>% h4(),
  
  "(K = Kludge, A = Accurate, I = Innacurate, + = Good Review/Correct Review,  - = Bad Review/Incorrect Review)" %>%  HTML(),
  
  
  inputPanel(
    
    fluidPage(
  
        numericInput(
          inputId = "prob_negative_when_correct_kludgy_accurate_1",
          label = "$$P(-)|(K, +, A)$$" %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_correct_not_kludgy_accurate_1",
          label = "$$P(-)|(!K, +, A)$$"  %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
      
        numericInput(
          inputId = "prob_negative_when_incorrect_kludgy_accurate_1",
          label = "$$P(-)|(K, -, A)$$"  %>%  withMathJax(),
          value = "0.85",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_incorrect_not_kludgy_accurate_1",
          label = "$$P(-)|(!K, -, A)$$"  %>%  withMathJax(),
          value = "0.85",
          step = 0.01
        ) ,
      
        
        numericInput(
          inputId = "prob_negative_when_correct_kludgy_inaccurate_1",
          label = "$$P(-)|(K, +, I)$$"  %>%  withMathJax(),
          value = "0.6",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_correct_not_kludgy_inaccurate_1",
          label = "$$P(-)|(!K, +, I)$$"  %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
      
        numericInput(
          inputId = "prob_negative_when_incorrect_kludgy_inaccurate_1",
          label = "$$P(-)|(K, -, I)$$"  %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_incorrect_not_kludgy_inaccurate_1",
          label = "$$P(-)|(!K, -, I)$$"  %>%  withMathJax(),
          value = "0.9",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "mean_time_accurate_1",
          label = "$$\\mu|A$$"  %>%  withMathJax() ,
          value = "1",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "mean_time_inaccurate_1",
          label = "$$\\mu|I$$"  %>%  withMathJax(),
          value = "1",
          step = "1"
        ) ,
        
      
        numericInput(
          inputId = "sd_time_meta_review_1",
          label = "$$\\sigma$$"  %>%  withMathJax(),
          value = "0.2",
          step = "0.1"
        ) 
  
  )
  
  )
  
  )

  ,
  
  
  

  wellPanel(

    
  style = "background:#aaddaa",


  "Parametrization 2" %>%  h3(),
      
  "Game" %>%  h4(),
  
  
  inputPanel(
    fluidPage(
        numericInput(
          inputId = "total_steps_2",
          label = "$$Steps$$" %>% withMathJax(),
          value = "3000",
          step = 1
        ), 
        
        numericInput(
          inputId = "entropy_factor_2",
          label = "$$H$$" %>% withMathJax(),
          value = "1.02",
          step = 0.01
        ) ,
  
        numericInput(
          inputId = "prob_review_2",
          label = "$$P(Review)$$" %>% withMathJax(),
          value = "0.5"
        ) ,
        
        numericInput(
          inputId = "prob_meta_review_2",
          label = "$$P(MetaReview|Review)$$"  %>% withMathJax(),
          value = "0.5"
        ) ,
        
        numericInput(
          inputId = "lambda_2",
          label = "$$\\lambda$$"  %>% withMathJax(),
          value = "1"
        ) ,
        
        numericInput(
          inputId = "n_executions_2",
          label = "$$executions$$"  %>% withMathJax(),
          value = "5"
        ) 
    )
      
  ),
  
  "Development Stage"  %>% h4(),
  
  "(D = Diligent, K = Kludge/Kludgy, R = Reworking)" %>% HTML(),
  
  inputPanel(

    fluidPage(    

        numericInput(
          inputId = "prob_diligent_2",
          label = "$$P(K)|D$$" %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
        numericInput(
          inputId = "prob_kludgy_2",
          label = "$$P(K)|K$$" %>%  withMathJax(),
          value = "0.9",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "mean_time_diligent_2",
          label = withMathJax("$$\\mu|(D, !R)$$"),
          value = "10",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "mean_time_kludgy_2",
          label = withMathJax("$$\\mu|(K, !R)$$"),
          value = "6",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "sd_time_develop_2",
          label = withMathJax("$$\\sigma|(!R)$$"),
          value = "2",
          step = "1"
        ) ,
  
        numericInput(
          inputId = "mean_time_rework_2",
          label = withMathJax("$$\\mu|R$$"),
          value = "3",
          step = "1"
        ) ,
  
        numericInput(
          inputId = "sd_time_rework_2",
          label = withMathJax("$$\\sigma|R$$"),
          value = "5",
          step = "1"
        ) 
    )
  
  ),
  
  
  "Review Stage"  %>% h4(),
  
  "(K = Kludge, C = Careful, N = Negligent)" %>% HTML(),
  
  inputPanel(
    
    fluidPage(
        
        numericInput(
          inputId = "mean_time_review_2",
          label = "$$\\mu$$",
          value = "1",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "sd_time_review_2",
          label = "$$\\sigma$$",
          value = "0.2",
          step = "1"
        ) ,
      
        
        numericInput(
          inputId = "prob_kludgy_review_when_kludge_careful_2",
          label = "$$P(K)|(K, C)$$" %>% withMathJax() ,
          value = "0.85"
        ) ,
      
        numericInput(
          inputId = "prob_kludgy_review_when_not_kludge_careful_2",
          label = "$$P(K)|(!K, C)$$" %>% withMathJax(),
          value = "0.1"
        ) ,
          
        numericInput(
          inputId = "prob_kludgy_review_when_kludge_negligent_2",
          label = "$$P(K)|(K, N)$$" %>% withMathJax(),
          value = "0.25"
        ) ,
      
        numericInput(
          inputId = "prob_kludgy_review_when_not_kludge_negligent_2",
          label = "$$P(K)|(!K, N)$$" %>% withMathJax(),
          value = "0.1"
        ) 
        
    )
  ),
        
  "Metareview Stage"  %>% h4(),
  
  "(K = Kludge, A = Accurate, I = Innacurate, + = Good Review/Correct Review,  - = Bad Review/Incorrect Review)" %>%  HTML(),
  
  
  inputPanel(
    
    fluidPage(
  
        numericInput(
          inputId = "prob_negative_when_correct_kludgy_accurate_2",
          label = "$$P(-)|(K, +, A)$$" %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_correct_not_kludgy_accurate_2",
          label = "$$P(-)|(!K, +, A)$$"  %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
      
        numericInput(
          inputId = "prob_negative_when_incorrect_kludgy_accurate_2",
          label = "$$P(-)|(K, -, A)$$"  %>%  withMathJax(),
          value = "0.85",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_incorrect_not_kludgy_accurate_2",
          label = "$$P(-)|(!K, -, A)$$"  %>%  withMathJax(),
          value = "0.85",
          step = 0.01
        ) ,
      
        
        numericInput(
          inputId = "prob_negative_when_correct_kludgy_inaccurate_2",
          label = "$$P(-)|(K, +, I)$$"  %>%  withMathJax(),
          value = "0.6",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_correct_not_kludgy_inaccurate_2",
          label = "$$P(-)|(!K, +, I)$$"  %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
      
        numericInput(
          inputId = "prob_negative_when_incorrect_kludgy_inaccurate_2",
          label = "$$P(-)|(K, -, I)$$"  %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_incorrect_not_kludgy_inaccurate_2",
          label = "$$P(-)|(!K, -, I)$$"  %>%  withMathJax(),
          value = "0.9",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "mean_time_accurate_2",
          label = "$$\\mu|A$$"  %>%  withMathJax() ,
          value = "1",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "mean_time_inaccurate_2",
          label = "$$\\mu|I$$"  %>%  withMathJax(),
          value = "1",
          step = "1"
        ) ,
        
      
        numericInput(
          inputId = "sd_time_meta_review_2",
          label = "$$\\sigma$$"  %>%  withMathJax(),
          value = "0.2",
          step = "0.1"
        ) 
  
  )
  
  )
  
  )

  
)
  
```


</details>


<br>




```{r, echo=FALSE}

  actionButton(
    inputId = "go",
    label = "Simulate!"
  )


```





```{r, echo=FALSE}
game_results <- eventReactive(eventExpr = input$go , valueExpr = {
  

  progress <- shiny::Progress$new()
  
  on.exit(progress$close())

  info <- list()
    
  values <- map(
    .x = names(input),
    .f = ~{
      if(.x %in% c("devs_1", "devs_2")){
        info[[.x]] <- hot_to_r(input[[.x]])
      }else{
        info[[.x]] <- input[[.x]]   
      }
      
    }
  )

  names(values) <- names(input)

  values_1 <- values[str_detect(string = names(values), pattern = "_1$")]
  names_1 <- names(values_1) %>% str_remove(pattern = "_1$")
  names(values_1) <- names_1
  
  
  values_2 <- values[str_detect(string = names(values), pattern = "_2$")]
  names_2 <- names(values_2) %>% str_remove(pattern = "_2$")
  names(values_2) <- names_2


  simulate_and_label <- function(round, values, progress, n_executions, memo = TRUE){

    if(memo){
      simulated <- simulate_game_simmer_memo(values, round)  
    }else{
      simulated <- simulate_game_simmer(values, round)  
    }
    
    
    progress$inc(1/n_executions)
    
    # saida <- list(
    #   data = simulated$data %>% 
    #     mutate(
    #       round = round
    #     ),
    #   
    #   entropy = simulated$entropy %>% 
    #     mutate(
    #       round = round
    #     )
    # )
    
    simulated

  }
  


  progress$set(message = "Simulating 1/2", value = 0)
  
  result_1 <- purrr::map(
    .x = 1:n_executions_1(),
    .f = ~simulate_and_label(
      round = .x,
      values = values_1,
      progress = progress,
      n_executions = n_executions_1()
    )
  )

  progress$set(message = "Simulating 2/2", value = 0)
  
  
  result_2 <- purrr::map(
    .x = 1:n_executions_2(),
    .f = ~simulate_and_label(
      round = .x,
      values = values_2,
      progress = progress,
      n_executions = n_executions_2()
    )
  )
  
  progress$set(message = "Simulating 2/2", value = 0)
  
  result_2 <- purrr::map(
    .x = 1:n_executions_2(),
    .f = ~simulate_and_label(
      round = .x,
      values = values_2,
      progress = progress,
      n_executions = n_executions_1()
    )
  )
    
  tictoc::toc()

  data_1 <- result_1 %>% 
    map2_df(
      .y = 1:n_executions_1(),
      .f = function(data, i){
        data$data %>% 
          mutate(
            round = i
          )
      }
    )
  

  entropy_1 <- result_1 %>% 
    map2_df(
      .y = 1:n_executions_1(),
      .f = function(data, i){
        data$entropy %>% 
          mutate(
            round = i
          )
      }
    )
  

  data_2 <- result_2 %>% 
    map2_df(
      .y = 1:n_executions_2(),
      .f = function(data, i){
        data$data %>% 
          mutate(
            round = i
          )
      }
    )
  

  entropy_2 <- result_2 %>% 
    map2_df(
      .y = 1:n_executions_2(),
      .f = function(data, i){
        data$entropy %>% 
          mutate(
            round = i
          )
      }
    )
  
    
  output_result <- list()
  
  output_result$data_1 <- data_1
  output_result$entropy_1 <- entropy_1
  output_result$data_2 <- data_2
  output_result$entropy_2 <- entropy_2
  
  
  output_result

})
  

```




```{r, echo=FALSE}


gera_graficos <- function(data, total_steps){
  
  
  n_charts <- 3
  
  total_steps = isolate(total_steps)
  
  data <- data %>% 
    mutate(
      developer = str_glue("Dev{developer}") %>% as.character() %>%  as.factor(),
      reviewer = str_glue("Rev{reviewer}") %>% as.character() %>%  as.factor()
    )
    
  progress <- shiny::Progress$new()
  
  on.exit(progress$close())

  progress$set(message = "Plotting results", value = 0)


  merges_kludge <- data %>% 
    filter(
      kludge %in% c(0,1)      
    ) %>% 
    group_by(
      pullrequest, rework, round, developer
    ) %>% 
    summarise(
      kludge = mean(kludge)
    ) %>% 
    group_by(
      round, developer
    ) %>% 
    summarise(
      kludge = mean(kludge)
    )
  

  kludge_plot <- ggplot(merges_kludge) +
    geom_density(
      aes(
        x = kludge,
        color = developer,
        fill = developer
      ),
      alpha = 0.2
    ) +
    theme_minimal() +
    theme(
      legend.position = "top",
      axis.text.x = element_text(angle = 90)
    ) +
    ggtitle(
      label = "% Kludge"
    ) +
    scale_x_continuous(
      labels = percent_format(accuracy = 1),
      limits = c(0,1)
    )

  progress$inc(1/n_charts)

  merged_prs_per_developer <- data %>% 
    filter(
      cur_stage == "Merge",
      phase == "End"
    ) %>% 
    group_by(
      round, developer
    ) %>% 
    summarise(
      n = n()
    )
    
  
  merged_prs_per_developer_plot <- ggplot(
    merged_prs_per_developer,
    aes(
      x = developer,
      y = n
    )
  ) +
    geom_violin(
      aes(
        fill = developer,
        color = developer
      ),
      alpha = 0.2,
      draw_quantiles = c(0.25, 0.5, 0.75)
    ) +
    geom_sina(
      aes(
        color = developer
      ),
      alpha = 0.6
    ) +
    theme_minimal() +
    theme(
      legend.position = "top",
      axis.text.x = element_text(angle = 90)
    ) +
    ggtitle(
      label = "Merges \n Developers payoff?"
    ) +
    scale_y_continuous(
      limits = c(0,NA)
    )

  progress$inc(1/n_charts)

  cumulative_merges <- data %>% 
    filter(
      cur_stage == "Merge",
      phase == "End"
    ) %>% 
    mutate(
      unitario = 1
    ) %>% 
    arrange(
      time
    ) %>% 
    group_by(
      round, developer
    ) %>% 
    mutate(
      cum_pr = cumsum(unitario)
    ) %>% 
    ungroup()
  
  cumulative_merges_total <- data %>% 
    filter(
      cur_stage == "Merge",
      phase == "End"
    ) %>% 
    mutate(
      unitario = 1
    ) %>% 
    arrange(
      time
    ) %>% 
    group_by(
      round
    ) %>% 
    mutate(
      cum_pr = cumsum(unitario)
    ) %>% 
    ungroup()
  

  cum_pr <- ggplot(
    cumulative_merges_total,
    aes(
      x = time,
      y = cum_pr
    ),
    ) + 
    geom_line(
      aes(
        group = interaction(round)
      ),
      alpha = 0.2
    ) +
    geom_smooth(
      size = 2,
      se = FALSE,
      color = "darkgreen"
    ) +
    theme_minimal() +
    theme(
      legend.position = "top"
    ) +
    ggtitle(
      label = "Cumulative Merges"
    ) +
    annotate(
      geom = "text",
      size = 5,
      fontface = "bold",
      x = max(cumulative_merges_total$time) + 100,
      y = last(
        cumulative_merges_total$cum_pr, order_by = cumulative_merges_total$time
      ),
      label = number(
        last(
          cumulative_merges_total$cum_pr, 
          order_by = cumulative_merges_total$time), accuracy = 1
        ),
      color = "darkgreen"
    ) +
    scale_y_continuous(
      limits = c(0, NA),
      sec.axis = sec_axis(identity)
    ) 

  
  final_merges <- cumulative_merges %>% 
    group_by(
      developer, round
    ) %>% 
    summarise(
      total_merges = last(cum_pr, order_by = time)
    ) %>% 
    group_by(
      developer
    ) %>% 
    summarise(
      total_merges = mean(total_merges)
    )
     
  cum_por_dev <- ggplot(
    cumulative_merges,
    aes(
      color = developer,
      x = time,
      y = cum_pr
    )
    ) + 
    geom_line(
      aes(
        group = interaction(round, developer)
      ),
      alpha = 0.2
    ) +
    geom_smooth(
      size = 2,
      se = FALSE
    ) +
    theme_minimal() +
    theme(
      legend.position = "top",
    ) +
    ggtitle(
      label = "Cumulative Merges"
    ) +
    geom_text_repel(
      data = final_merges,
      x = max(cumulative_merges$time) + 100,
      size = 5,
      fontface = "bold",
      aes(
        y = total_merges,
        label = number(total_merges, accuracy = 1),
        color = developer
      )
    ) +
    scale_y_continuous(
      limits = c(0, NA),
      sec.axis = sec_axis(identity)
    ) 

  cumulative_merges <- data %>% 
    filter(
      cur_stage == "Merge",
      phase == "End"
    ) %>% 
    mutate(
      unitario = 1
    ) %>% 
    arrange(
      time
    ) %>% 
    group_by(
      round, developer
    ) %>% 
    mutate(
      cum_pr = cumsum(unitario)
    ) %>% 
    ungroup()
  
  progress$inc(1/n_charts)
  

  merged_prs_per_time <- data %>% 
    filter(
      cur_stage == "Merge",
      phase == "End"
    ) %>% 
    arrange(time) %>% 
    group_by(round) %>% 
    mutate(
      merges_300 = slide_index_dbl(
        .x = time,
        .i = time,
        .f = ~length(.x),
        .before = 300,
        .complete = TRUE
      )
    ) %>% 
    ungroup()

  merges_per_time <- ggplot(
    merged_prs_per_time,
    aes(
      x = time,
      y = merges_300
    )
    ) + 
    geom_line(
      aes(
        group = round
      ),
      alpha = 0.1
    ) +
    geom_smooth(
      size = 2,
      se = FALSE,
      color = "darkgreen"
    ) +
    theme_minimal() +
    theme(
      legend.position = "top",
    ) +
    ggtitle(
      label = "Merges last 300 steps"
    ) +
    scale_y_continuous(
      limits = c(0, NA),
      sec.axis = sec_axis(identity)
    ) 


  merged_prs_per_time_per_developer <- data %>% 
    filter(
      cur_stage == "Merge",
      phase == "End"
    ) %>% 
    arrange(time) %>% 
    group_by(round, developer) %>% 
    mutate(
      merges_300 = slide_index_dbl(
        .x = time,
        .i = time,
        .f = ~length(.x),
        .before = 300,
        .complete = TRUE
      )
    ) %>% 
    ungroup()

  merges_per_time_per_developer <- ggplot(
    merged_prs_per_time_per_developer,
    aes(
      x = time,
      y = merges_300,
      color = developer
    )
    ) + 
    geom_line(
      aes(
        group = interaction(round, developer)
      ),
      alpha = 0.2
    ) +
    geom_smooth(
      size = 2,
      se = FALSE,
      aes(
        group = developer
      )
    ) +
    theme_minimal() +
    theme(
      legend.position = "top",
    ) +
    ggtitle(
      label = "Merges last 300 steps"
    ) +
    scale_y_continuous(
      limits = c(0, NA),
      sec.axis = sec_axis(identity)
    ) 


  metareviews_rate <- data %>% 
    filter(
      cur_stage == "MetaReview",
      phase == "End"
    ) %>% 
    group_by(
      round, reviewer
    ) %>% 
    summarize(
      good = sum(metareview_good == 1)/n()
    ) %>% 
    ungroup()
  
  
  metareviews_rate_plot <- ggplot(
    metareviews_rate,
    aes(
      x = reviewer,
      y = good
    )
  ) +
    geom_violin(
      aes(
        fill = reviewer,
        color = reviewer
      ),
      alpha = 0.2,
      draw_quantiles = c(0.25, 0.5, 0.75)
    ) +
    geom_sina(
      aes(
        color = reviewer
      ),
      alpha = 0.6
    ) +
    theme_minimal() +
    theme(
      legend.position = "top",
      axis.text.x = element_text(angle = 90)
    ) +
    ggtitle(
      label = "Good MetaReviews Rate per reviewer\n(reviewer's payoff?)"
    ) +
    scale_y_continuous(
      limits = c(0,1),
      labels = percent_format(accuracy = 1)
    )


  stages_time <- data %>% 
    filter(
      seized == 1
    ) %>% 
    group_by(
      pullrequest,
      round,
      cur_stage,
      phase,
      rework,
      developer,
      reviewer
    ) %>% 
    summarise(
      time = min(time)
    ) %>% 
    ungroup() %>% 
    pivot_wider(
      names_from = phase,
      values_from = c(time, developer, reviewer)
    ) %>% 
    replace_na(
      list(time_End = total_steps)
    ) %>% 
    filter(
      cur_stage %in% c("Development", "Review", "MetaReview")
    ) %>% 
    mutate(
      cur_stage = if_else(cur_stage == "Development" & rework > 0, "Rework", cur_stage ),
      duration = time_End - time_Start,
      alocation = case_when(
        cur_stage %in% c("Development", "Rework", "MetaReview") ~ developer_End %>%  as.character(),
        cur_stage %in% c("Review") ~ reviewer_End %>%  as.character()
      )
    ) %>% 
    group_by(
      alocation, cur_stage, round
    ) %>% 
    summarise(frac_time = sum(duration)/total_steps)      
    
  time_idle <- stages_time %>% 
    group_by(
      alocation, round
    ) %>% 
    summarise(
      frac_time = 1 - sum(frac_time)
    ) %>% 
    mutate(
      cur_stage = "Idle"
    )
    

  frac_total = bind_rows(
    time_idle,
    stages_time
  ) %>% 
    filter(!is.na(alocation))
    
    
  frac_time_plot <- ggplot(
    frac_total,
    aes(
      x = cur_stage,
      y = frac_time
    )
    ) +
    geom_violin(
      aes(
        color = cur_stage,
        fill = cur_stage
      ),
      alpha = 0.2,
      draw_quantiles = c(0.25, 0.5, 0.75),
      scale = "width"
    ) +
    geom_sina(
      aes(
        color = cur_stage,
        fill = cur_stage
      ),
      alpha = 0.6
    ) +
    theme_minimal() +
    facet_wrap(~alocation, ncol = 2) +
    scale_y_continuous(
      label = percent_format()
    ) +
    theme(
      legend.position = "top"
    )
    
  
  patch <- (kludge_plot | merged_prs_per_developer_plot | metareviews_rate_plot) / cum_pr / cum_por_dev / merges_per_time / merges_per_time_per_developer / frac_time_plot + 
    plot_layout(
      heights = c(1, 1, 1, 1, 1, 3)
    )
  
  patch + plot_annotation(
    title = isolate("Results after {n_executions_1()} executions" %>%  str_glue()),
    theme = theme(plot.title = element_text(size = 20))
  )
  
  
  
} 


output$plot_results_1 <-  renderPlot({
  
  gera_graficos(data = game_results()$data_1, total_steps = input$total_steps_1 )  
  
})


output$plot_results_2 <-  renderPlot({
  
  gera_graficos(data = game_results()$data_2, total_steps = input$total_steps_2 )  
  
})


splitLayout(

  plotOutput(outputId = "plot_results_1", height = "2000px" ),
  plotOutput(outputId = "plot_results_2", height = "2000px" )
)



```



```{r, echo=FALSE}

# renderPlot({
# 
#   data <- game_results()$data
# 
# 
#   max_start = max(data$time)
#   
#   trajectories <- data %>% 
#     dplyr::select(
#       time,
#       pullrequest,
#       cur_stage,
#       rework,
#       phase
#     ) %>% 
#     group_by(
#       pullrequest
#     ) %>% 
#     mutate(
#       start_pr = min(time)
#     ) %>% 
#     pivot_wider(
#       names_from = phase,
#       values_from = time
#     ) %>% 
#     janitor::clean_names() %>% 
#     replace_na(
#       list(end = max_start)
#     )
#     
#     ggplot(trajectories) +
#       geom_segment(
#         aes(
#           y = start_pr,
#           yend = start_pr,
#           x = start - start_pr,
#           xend = end - start_pr,
#           color = cur_stage
#         )
#         
#       )
#   
# },
# 
# height = 800
# 
# )


```








```{r, echo=FALSE}


# renderReactable(
#   reactable(game_results()$data)
# )


```


<!-- # Many Simulations -->


<!-- ```{r, echo=FALSE} -->


<!-- possible_params <- read_rds("data/params.rds") -->

<!-- output$hot <- renderRHandsontable({ -->

<!--     DF = tibble(param = "total_steps", value = "500" ) -->

<!--     rhandsontable(DF, width = 550) %>% -->
<!--         hot_col(col = "param", type = "dropdown", source = possible_params ) -->

<!--   }) -->


<!-- inputPanel( -->

<!--   verticalLayout( -->
<!--     rHandsontableOutput("hot", width = 600, height = 600)  , -->
<!--     actionButton(inputId = "gotable",  label = "Go!") -->
<!--   ) -->

<!-- ) -->


<!-- renderReactable({ -->

<!--     input$gotable -->
<!--     hot = isolate(input$hot) -->
<!--     if (!is.null(hot)) { -->
<!--       reactable(hot_to_r(input$hot)) -->
<!--     }   -->

<!-- }) -->





<!-- ``` -->





```{r}


observe({


  updateNumericInput(
    inputId = "prob_review_1",
    value = input$process_fraction_review_1/100
  )

  updateNumericInput(
    inputId = "prob_meta_review_1",
    value = input$process_fraction_metareview_1/100
  )
  
  harm_degree_1 <- input$characteristics_kludges_harmful_1
  

  if(!is.null(harm_degree_1)){
    
    entropy_number_1 <- likert_harm %>% 
      filter(
        description == harm_degree_1
      ) %>% 
      pull(entropy)
    
    updateNumericInput(
      inputId = "entropy_factor_1",
      value = entropy_number_1
    )

  }
  

  updateNumericInput(
    inputId = "prob_review_2",
    value = input$process_fraction_review_2/100
  )

  updateNumericInput(
    inputId = "prob_meta_review_2",
    value = input$process_fraction_metareview_2/100
  )
  
  harm_degree_2 <- input$characteristics_kludges_harmful_2
  

  if(!is.null(harm_degree_2)){
    
    entropy_number_2 <- likert_harm %>% 
      filter(
        description == harm_degree_2
      ) %>% 
      pull(entropy)
    
    updateNumericInput(
      inputId = "entropy_factor_2",
      value = entropy_number_2
    )

  }
  
  
  updateNumericInput(
    inputId = "prob_review_game",
    value = input$process_fraction_review_game/100
  )

  updateNumericInput(
    inputId = "prob_meta_review_game",
    value = input$process_fraction_metareview_game/100
  )
  
  harm_degree_game <- input$characteristics_kludges_harmful_game
  

  if(!is.null(harm_degree_game)){
    
    entropy_number_game <- likert_harm %>% 
      filter(
        description == harm_degree_game
      ) %>% 
      pull(entropy)
    
    updateNumericInput(
      inputId = "entropy_factor_game",
      value = entropy_number_game
    )

  }
  
    
  
    
})





```



```{r}

renderText(
  simulation_results()
)

```

# Game




```{r, echo=FALSE}
#user inputs


n_executions_game <- reactive({
  
  input$n_executions_game
  
})




splitLayout(

  wellPanel( 

    style = "background:#66bbff",
  

    "Parametrization Game" %>%  h3(),

      
    "Players" %>%  h4(),
    
    wellPanel(
      
      
    
    splitLayout(cellWidths = c("50%", "50%"),
    
    verticalLayout(  
    "Developers" %>% h5(),
      rHandsontableOutput  ("devs_game", width = 400, height = 250)  
    )
    
    )
    
    ),
    
    
    splitLayout(
    
    verticalLayout(  
    "Development Process" %>%  h4(),
    
    wellPanel(
    
      sliderInput("process_fraction_review_game",label="% of pull requests reviewed", min = 0, max = 100, post  = " %", value = 50, step = 5),
      
      sliderInput("process_fraction_metareview_game",label="% of reviews metareviewed", min = 0, max = 100, post  = " %", value = 50, step = 5)
    
        
    
    )
    )
    ,
    
    verticalLayout(  
    "Development" %>%  h4(),
    
    
    wellPanel(
    
      radioButtons(
        inputId = "characteristics_kludges_harmful_game",
        label = "Kludges harmful",
        choices = likert_harm$description
      )
      
    
    )
    
    )
    
    )
  
  )
    

)


output$devs_game <- renderRHandsontable({

    DF = tibble(
      strategy_dev = c(actions$Diligent, actions$Diligent, actions$Diligent),
      strategy_rev = c(actions$Careful, actions$Careful, actions$Careful ),
      strategy_meta = c(actions$Accurate, actions$Accurate, actions$Accurate )
    )

    rhandsontable(DF, width = 400) %>%
        hot_col(
          col = "strategy_dev",
          type = "dropdown",
          source = c(actions$Diligent, actions$Kludgy)  
        ) %>% 
        hot_col(
          col = "strategy_rev",
          type = "dropdown",
          source = c(actions$Careful, actions$Negligent)  
        ) %>% 
        hot_col(
          col = "strategy_meta",
          type = "dropdown",
          source = c(actions$Accurate, actions$Inaccurate)  
        ) 

  })




```


<br>

<details>
  <summary>Click if you want to see details</summary>


```{r, echo=FALSE}


splitLayout(



  wellPanel(
    
    
  style = "background:#66bbff",


  "Parametrization 1" %>%  h3(),
    
  
  "Game" %>%  h4(),
  
  
  inputPanel(
    fluidPage(
        numericInput(
          inputId = "total_steps_game",
          label = "$$Steps$$" %>% withMathJax(),
          value = "500",
          step = 1
        ), 
        
        numericInput(
          inputId = "entropy_factor_game",
          label = "$$H$$" %>% withMathJax(),
          value = "1.02",
          step = 0.01
        ) ,
  
        numericInput(
          inputId = "prob_review_game",
          label = "$$P(Review)$$" %>% withMathJax(),
          value = "0.5"
        ) ,
        
        numericInput(
          inputId = "prob_meta_review_game",
          label = "$$P(MetaReview|Review)$$"  %>% withMathJax(),
          value = "0.5"
        ) ,
        
        numericInput(
          inputId = "lambda_game",
          label = "$$\\lambda$$"  %>% withMathJax(),
          value = "1"
        ) ,
          
        numericInput(
          inputId = "n_executions_game",
          label = "$$executions$$"  %>% withMathJax(),
          value = "10"
        ) 
    )
      
  ),
  
  "Development Stage"  %>% h4(),
  
  "(D = Diligent, K = Kludge/Kludgy, R = Reworking)" %>% HTML(),
  
  inputPanel(

    fluidPage(    

        numericInput(
          inputId = "prob_diligent_game",
          label = "$$P(K)|D$$" %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
        numericInput(
          inputId = "prob_kludgy_game",
          label = "$$P(K)|K$$" %>%  withMathJax(),
          value = "0.9",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "mean_time_diligent_game",
          label = withMathJax("$$\\mu|(D, !R)$$"),
          value = "10",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "mean_time_kludgy_game",
          label = withMathJax("$$\\mu|(K, !R)$$"),
          value = "6",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "sd_time_develop_game",
          label = withMathJax("$$\\sigma|(!R)$$"),
          value = "2",
          step = "1"
        ) ,
  
        numericInput(
          inputId = "mean_time_rework_game",
          label = withMathJax("$$\\mu|R$$"),
          value = "3",
          step = "1"
        ) ,
  
        numericInput(
          inputId = "sd_time_rework_game",
          label = withMathJax("$$\\sigma|R$$"),
          value = "5",
          step = "1"
        ) 
    )
  
  ),
  
  
  "Review Stage"  %>% h4(),
  
  "(K = Kludge, C = Careful, N = Negligent)" %>% HTML(),
  
  inputPanel(
    
    fluidPage(
        
        numericInput(
          inputId = "mean_time_review_game",
          label = "$$\\mu$$",
          value = "1",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "sd_time_review_game",
          label = "$$\\sigma$$",
          value = "0.2",
          step = "1"
        ) ,
      
        
        numericInput(
          inputId = "prob_kludgy_review_when_kludge_careful_game",
          label = "$$P(K)|(K, C)$$" %>% withMathJax() ,
          value = "0.85"
        ) ,
      
        numericInput(
          inputId = "prob_kludgy_review_when_not_kludge_careful_game",
          label = "$$P(K)|(!K, C)$$" %>% withMathJax(),
          value = "0.1"
        ) ,
          
        numericInput(
          inputId = "prob_kludgy_review_when_kludge_negligent_game",
          label = "$$P(K)|(K, N)$$" %>% withMathJax(),
          value = "0.25"
        ) ,
      
        numericInput(
          inputId = "prob_kludgy_review_when_not_kludge_negligent_game",
          label = "$$P(K)|(!K, N)$$" %>% withMathJax(),
          value = "0.1"
        ) 
        
    )
  ),
        
  "Metareview Stage"  %>% h4(),
  
  "(K = Kludge, A = Accurate, I = Innacurate, + = Good Review/Correct Review,  - = Bad Review/Incorrect Review)" %>%  HTML(),
  
  
  inputPanel(
    
    fluidPage(
  
        numericInput(
          inputId = "prob_negative_when_correct_kludgy_accurate_game",
          label = "$$P(-)|(K, +, A)$$" %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_correct_not_kludgy_accurate_game",
          label = "$$P(-)|(!K, +, A)$$"  %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
      
        numericInput(
          inputId = "prob_negative_when_incorrect_kludgy_accurate_game",
          label = "$$P(-)|(K, -, A)$$"  %>%  withMathJax(),
          value = "0.85",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_incorrect_not_kludgy_accurate_game",
          label = "$$P(-)|(!K, -, A)$$"  %>%  withMathJax(),
          value = "0.85",
          step = 0.01
        ) ,
      
        
        numericInput(
          inputId = "prob_negative_when_correct_kludgy_inaccurate_game",
          label = "$$P(-)|(K, +, I)$$"  %>%  withMathJax(),
          value = "0.6",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_correct_not_kludgy_inaccurate_game",
          label = "$$P(-)|(!K, +, I)$$"  %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
      
        numericInput(
          inputId = "prob_negative_when_incorrect_kludgy_inaccurate_game",
          label = "$$P(-)|(K, -, I)$$"  %>%  withMathJax(),
          value = "0.1",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "prob_negative_when_incorrect_not_kludgy_inaccurate_game",
          label = "$$P(-)|(!K, -, I)$$"  %>%  withMathJax(),
          value = "0.9",
          step = 0.01
        ) ,
        
        numericInput(
          inputId = "mean_time_accurate_game",
          label = "$$\\mu|A$$"  %>%  withMathJax() ,
          value = "1",
          step = "1"
        ) ,
      
        numericInput(
          inputId = "mean_time_inaccurate_game",
          label = "$$\\mu|I$$"  %>%  withMathJax(),
          value = "1",
          step = "1"
        ) ,
        
      
        numericInput(
          inputId = "sd_time_meta_review_game",
          label = "$$\\sigma$$"  %>%  withMathJax(),
          value = "0.2",
          step = "0.1"
        ) 
  
  )
  
  )
  
  )

  
)
  
```


</details>




```{r}

  actionButton(
    inputId = "solve",
    label = "Solve Games"
  )


```


```{r}

  actionButton(
    inputId = "solve_all",
    label = "Solve All Games"
  )


```


```{r}

  actionButton(
    inputId = "solve_all_no_memo",
    label = "Solve All Games No Memo"
  )



```




```{r}

  actionButton(
    inputId = "read_solve_all",
    label = "Read All Games"
  )



```





```{r}

update_input <- function(input, process_fraction_review_game, process_fraction_metareview_game, characteristics_kludges_harmful_game ){


  input$prob_review_game = process_fraction_review_game/100
  input$prob_meta_review_game = process_fraction_metareview_game/100

  harm_degree_game <- characteristics_kludges_harmful_game

  if(!is.null(harm_degree_game)){
    
    entropy_number_game <- likert_harm %>% 
      filter(
        description == harm_degree_game
      ) %>% 
      pull(entropy)
    
    input$entropy_factor_game = entropy_number_game

  }
  
  input
  
}



simulation_results <- eventReactive(eventExpr = input$solve , valueExpr = {

  simulate_core(input = input, n_executions_game = n_executions_game() )  

})


simulate_all <- eventReactive(eventExpr = input$solve_all , valueExpr = {

  
  tib_process_fraction_review_game <-  tibble(
    process_fraction_review_game = c(0, 50, 100)
  )
  
  tib_process_fraction_metareview_game <-  tibble(
    process_fraction_metareview_game = c(0, 50, 100)
  )
  
  tib_characteristics_kludges_harmful_game <- tibble(
    characteristics_kludges_harmful_game = likert_harm$description,
    order = likert_harm$entropy
  )
  
  

  all_params_all <- crossing(
    tib_process_fraction_review_game,
    tib_process_fraction_metareview_game,
    tib_characteristics_kludges_harmful_game
  ) %>% 
    arrange(
      process_fraction_review_game,
      process_fraction_metareview_game,
      order
    ) %>% 
    mutate(
      instance = row_number()
    )
  

  files <- list.files(pattern = "[0-9]+.rds") %>% 
    str_remove("\\.rds") %>% 
    as.integer() %>% 
    enframe() %>% 
    rename(
      instance = value
    )
  

  all_params <- all_params_all %>% 
    anti_join(files, by = "instance") %>% 
    sample_n(size = nrow(.))


  for (i in 1:nrow(all_params)){
    

    info <- list()
    
    values <- map(
      .x = names(input),
      .f = ~{
        info[[.x]] <- input[[.x]]   
      }
    )
    
    names(values) <- names(input)
    
    this_input <- update_input(
      input = values, 
      process_fraction_review_game = all_params$process_fraction_review_game[i],
      process_fraction_metareview_game = all_params$process_fraction_metareview_game[i],
      characteristics_kludges_harmful_game = all_params$characteristics_kludges_harmful_game[i]
    )
    
    

    simulate_core_memo(input = this_input, n_executions_game = n_executions_game() )    
    
    write_rds(all_params$instance[i], paste0( all_params$instance[i], ".rds"))
    
    
  }
  

})



read_all <- eventReactive(eventExpr = input$read_solve_all , valueExpr = {

  

  tib_process_fraction_review_game <-  tibble(
    process_fraction_review_game = c(0, 25, 50, 75, 100)
  )
  
  tib_process_fraction_metareview_game <-  tibble(
    process_fraction_metareview_game = c(0, 25, 50, 75, 100)
  )
  
  tib_characteristics_kludges_harmful_game <- tibble(
    characteristics_kludges_harmful_game = likert_harm$description,
    order = likert_harm$entropy
  )
  
  all_params_all <- crossing(
    tib_process_fraction_review_game,
    tib_process_fraction_metareview_game,
    tib_characteristics_kludges_harmful_game
  ) %>% 
    arrange(
      process_fraction_review_game,
      process_fraction_metareview_game,
      order
    ) %>% 
    mutate(
      instance = row_number()
    )
  
  
  

  files <- list.files(pattern = "[0-9]+.rds") %>% 
    str_remove("\\.rds") %>% 
    as.integer() %>% 
    enframe() %>% 
    rename(
      instance = value
    )
  

  all_params <- all_params_all %>% 
    semi_join(files, by = "instance") %>% 
    sample_n(size = nrow(.))

  
  saida <- list() 

  for (i in 1:nrow(all_params)){
    

    info <- list()
    
    values <- map(
      .x = names(input),
      .f = ~{
        info[[.x]] <- input[[.x]]   
      }
    )
    
    names(values) <- names(input)
    
    this_input <- update_input(
      input = values, 
      process_fraction_review_game = all_params$process_fraction_review_game[i],
      process_fraction_metareview_game = all_params$process_fraction_metareview_game[i],
      characteristics_kludges_harmful_game = all_params$characteristics_kludges_harmful_game[i]
    )
     
    print(i)
    print(all_params$instance[i])
    
    elemento <- simulate_core_memo(input = this_input, n_executions_game = n_executions_game(), solve_game = TRUE  )    

    saida[[i]] <- elemento    
    
    saida[[i]]$instance <-  all_params$instance[i]
        
  }


  eqs <- map_df(
    .x = saida,
    .f = ~{
      .x$eqs %>% 
        mutate(
          instance = .x$instance
        )
    }
  ) %>% 
    inner_join(
      all_params,
      by = "instance"
    )

  
  results <- map_df(
    .x = saida,
    .f = ~{
      .x$resultados %>% 
        mutate(
          instance = .x$instance
        )
    }
  ) %>% 
    inner_join(
      all_params,
      by = "instance"
    )

  write_rds(eqs, "solved-games/data/eqs.rds")
  write_rds(results, "solved-games/data/results.rds")
  
  
  saida

})




```

```{r}

renderText(
  simulate_all()
)


```


```{r}



```



```{r}

renderText(
  read_all()
)


```



```{r}

observeEvent( input$solve_all_no_memo , {

  
  

  tib_process_fraction_review_game <-  tibble(
    process_fraction_review_game = c(0, 50, 100)
  )
  
  tib_process_fraction_metareview_game <-  tibble(
    process_fraction_metareview_game = c(0, 50, 100)
  )
  
  harm_degrees <- c("No", "Moderately", "A great deal")
  
  tib_characteristics_kludges_harmful_game <- tibble(
    # characteristics_kludges_harmful_game = likert_harm$description,
    characteristics_kludges_harmful_game = harm_degrees,
    order = c(1, 1.05, 1.1)
  )
  

  all_params_all <- crossing(
    tib_process_fraction_review_game,
    tib_process_fraction_metareview_game,
    tib_characteristics_kludges_harmful_game
  ) %>% 
    arrange(
      process_fraction_review_game,
      process_fraction_metareview_game,
      order
    ) %>% 
    mutate(
      instance = row_number()
    )
  
  
  browser()

  files <- list.files(pattern = "[0-9]+aaaaaaa.rds") %>% 
    str_remove("\\.rds") %>% 
    as.integer() %>% 
    enframe() %>% 
    rename(
      instance = value
    )

  all_params <- all_params_all %>% 
    sample_n(size = nrow(.)) %>% 
    #retirar
    # filter(
    #   process_fraction_review_game == 0,
    #   process_fraction_metareview_game == 0,
    #   characteristics_kludges_harmful_game == "No"
    # )
    identity()

  saida <- list()
  
  
  #retirar
  for (i in 21:nrow(all_params)){
  # for (i in sample(x = 1:nrow(all_params), size = 1)){
    

    info <- list()
    
    values <- map(
      .x = names(input),
      .f = ~{
        info[[.x]] <- input[[.x]]   
      }
    )
    
    names(values) <- names(input)
    
    this_input <- update_input(
      input = values, 
      process_fraction_review_game = all_params$process_fraction_review_game[i],
      process_fraction_metareview_game = all_params$process_fraction_metareview_game[i],
      characteristics_kludges_harmful_game = all_params$characteristics_kludges_harmful_game[i]
    )
    
    tictoc::tic("testando")
    #mexer
    elemento <- simulate_core(
      input = this_input, 
      n_executions_game = n_executions_game(), 
      #paralelo
      run_parallel = TRUE, 
      use_memo = FALSE, 
      solve_game = TRUE 
    )
    

    tictoc::toc()
    

    saida[[i]] <- elemento    
    
    saida[[i]]$instance <-  all_params$instance[i]
    
    print("#############################################")
    print(i)
    print("#############################################")
    
    write_rds(saida[[i]], str_glue("saida_final_{i}"))
    
    
  }

  print("foi")


  eqs <- map_df(
    .x = saida,
    .f = ~{
      .x$eqs %>% 
        mutate(
          instance = .x$instance
        )
    }
  ) %>% 
    inner_join(
      all_params,
      by = "instance"
    )
  
  
  results <- map_df(
    .x = saida,
    .f = ~{
      .x$resultados %>% 
        mutate(
          instance = .x$instance
        )
    }
  ) %>% 
    inner_join(
      all_params,
      by = "instance"
    )
  
  write_rds(eqs, "solved-games/data/eqs.rds")
  write_rds(results, "solved-games/data/results.rds")
  
  
  
  
})



```


