---
title: "simulation analysis"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(DBI)

knitr::opts_chunk$set(echo = TRUE)

con_db <- dbConnect(RSQLite::SQLite(), "db/log.db")

dbListTables(con_db)
  




```


```{r}
create <- "create index label_eqs on eqs(label)"
dbExecute(con_db, create)
create <- "create index i_eqs on eqs(i)"
dbExecute(con_db, create)

create <- "create index label_params on params(label)"
dbExecute(con_db, create)
create <- "create index i_params on params(i)"
dbExecute(con_db, create)


create <- "create index label_results on results(label)"
dbExecute(con_db, create)
create <- "create index i_results on results(i)"
dbExecute(con_db, create)

create <- "create index label_simulations on simulations(label)"
dbExecute(con_db, create)
create <- "create index i_simulations on simulations(i)"
dbExecute(con_db, create)
```


```{r}
eqs <- tbl(con_db, "eqs") %>% 
  collect() 


params <- tbl(con_db, "params") %>% 
  collect()


results <- tbl(con_db, "results") %>% 
  collect()


simulations <- tbl(con_db, "simulations") %>% 
  collect() 



```



```{r}


means <-  results %>% 
  group_by(
    dev,
    strategy_dev
  ) %>% 
  summarise(
    payoff = mean(payoff)
  )


means %>% 
  ggplot() +
  geom_col(
    aes(
      x = dev,
      y = payoff
    )
  ) +
  facet_grid(
    ~strategy_dev
  )


```




```{r}


results %>% 
  ggplot(
    aes(
      y = payoff,
      x = dev,
    )
  ) +
  geom_violin(
    aes(
      group = dev
    )
  ) +
  facet_grid(
    strategy_dev~.
  ) +
  geom_point(
    data = means,
    size = 4
  )
  
  


```





```{r}


param_strategy_dev <- params %>% 
  select(
    dev,
    strategy_dev,
    combination
  )


param_tres_kludges <- params %>% 
  select(
    dev,
    strategy_dev,
    combination
  ) %>% 
  group_by(
    combination
  ) %>% 
  mutate(
    n_kludges = sum(strategy_dev == "Kludgy")
  ) %>% 
  ungroup() %>% 
  filter(
    n_kludges == 3
  ) 


results_tres_kludges <- results %>% 
  filter(
    combination %in% param_tres_kludges$combination
  )



means <-  results_tres_kludges %>% 
  group_by(
    dev,
    strategy_dev
  ) %>% 
  summarise(
    payoff = mean(payoff)
  )



results_tres_kludges %>% 
  ggplot(
    aes(
      y = payoff,
      x = dev,
    )
  ) +
  geom_violin(
    aes(
      group = dev
    )
  ) +
  facet_grid(
    strategy_dev~.
  ) +
  geom_point(
    data = means,
    size = 4
  )
  


```



```{r}

results_less_kludge <- results %>% 
  filter(
    dev == 3
  ) %>% 
  slice_min(
    order_by = payoff
  )


results_more_kludge <- results %>% 
  filter(
    dev == 3
  ) %>% 
  slice_max(
    order_by = payoff
  )



```
```{r}

more <- 366

less <- 103


params_more <- params %>% 
  filter(
    combination == more
  ) %>% 
  mutate(
    across(
      .cols = everything(),
      .fns = as.character
    )
  ) %>% 
  pivot_longer(
    cols = everything(),
    names_to = "param",
    values_to = "value"
  )




params_less <- params %>% 
  filter(
    combination == less
  ) %>% 
  mutate(
    across(
      .cols = everything(),
      .fns = as.character
    )
  ) %>% 
  pivot_longer(
    cols = everything(),
    names_to = "param",
    values_to = "value"
  )



comparison <- bind_cols(params_less, params_more)


```


```{r}


one_params <- params %>% 
  filter(
    combination == 101
  ) %>% 
  select(
    dev,
    strategy_dev
  ) %>% 
  view()


results %>% 
  filter(
    combination == 101
  ) %>% 
  view()

one_simulation <- simulations %>% 
  filter(
    combination == 101,
    replication == 1,
    execution == 1
  ) 
  
  
starts <- one_simulation %>%    
  group_by(
    pullrequest
  ) %>% 
  slice_min(
    order_by = time,
    n = 1
  )


ends <- one_simulation %>%    
  filter(
    phase == "End",
    cur_stage == "Development"
  ) %>% 
  group_by(
    pullrequest
  ) %>% 
  slice_max(
    order_by = time,
    n = 1
  ) %>% 
  ungroup()

ends %>% 
  group_by(
    developer
  ) %>% 
  summarise(
    n = n()
  ) %>% 
  view()


starts_rename <-  starts %>% 
  select(
    time_start = time,
    pullrequest,
    developer
  ) 

ends_rename <-  ends %>% 
  select(
    time_end = time,
    pullrequest,
    developer
  ) 
  
  
duration <- starts_rename %>% 
  full_join(
    ends_rename,
    by = c("pullrequest")
  )



cumul_starts <- starts %>% 
  select(
    developer,
    time,
    i
  ) %>% 
  ungroup() %>% 
  pivot_wider(
    names_from = developer,
    values_from = i,
    values_fill = 0
  ) %>% 
  mutate(
    across(
      .cols = matches("[0-9]"),
      .fns = cumsum 
    )
  )  %>% 
  view()

  







```

