---
title: "Game Simulation"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(DBI)
library(ggforce)
library(ggiraph)
library(scales)


conexao <- dbConnect(RSQLite::SQLite(), "db/log.db" )


n_devs <- 3

params <- tbl(conexao, "params") %>% 
  collect() %>% 
  select(
    prob_review,
    entropy_factor,
    i
  ) %>% 
  distinct()

eqs <- tbl(conexao, "eqs") %>% 
  collect() %>% 
  distinct()





params_eqs <- params %>% 
  left_join(
    eqs,
    by = "i"
  )

params_eqs %>% 
  arrange(
    prob_review,
    entropy_factor
  )


results <- tbl(conexao, "results") %>% 
  collect() %>% 
  mutate(
    complete_strategy = str_glue("{strategy_dev}_{strategy_rev}_{strategy_meta}")
  ) %>% 
  group_by(
    i, combination, dev, complete_strategy
  ) %>% 
  summarise(
    merges = mean(merges)
  ) %>% 
  ungroup() %>% 
  pivot_wider(
    values_from = c(complete_strategy, merges),
    names_glue = "{.value}_{dev}" ,
    names_from = "dev"
  ) %>%
  rowwise() %>% 
  mutate(
    total_merges = sum(c_across(cols = starts_with("merges_")) )
  ) %>% 
  ungroup()



company_payoff <- params_eqs %>% 
  inner_join(
    results,
    by = c(str_glue("complete_strategy_{1:n_devs}"),"i")
  )
  

results_long <- tbl(conexao, "results") %>% 
  collect() %>% 
  mutate(
    complete_strategy = str_glue("{strategy_dev}_{strategy_rev}_{strategy_meta}")
  ) %>% 
  group_by(
    i, combination, dev, complete_strategy
  ) %>% 
  summarise(
    merges = mean(merges)
  ) %>% 
  ungroup()


```





```{r}




dados_grafico <- params_eqs %>% 
  mutate(
    across(
      .cols = starts_with("complete_"),
      .fns = ~str_sub(string = .x, start = 1, end = 1)
    )    
  ) %>% 
  mutate(
    igual_1 = complete_strategy_1 == complete_strategy_2,
    igual_2 = complete_strategy_2 == complete_strategy_3,
  ) %>% 
  mutate(
    strategy =  complete_strategy_1 
  ) 
  


```


```{r}


create_plot <- function(data, fill_col = "strategy", fill_name = "Strategy", selectable = TRUE){

  if(fill_col == "strategy"){
    fill_scale_layer  <- scale_fill_manual(
      values = c(D = "darkgreen", K = "darkred" )
    )
    
    format_function <- identity
    
    plot_data <-  data %>%
      mutate(
        content_tiles = .data[[fill_col]]
      )
    
    
  } else{
    fill_scale_layer  <- scale_fill_gradient(
      low = "darkred",
      high = "darkgreen"
    )  
    
    plot_data <-  data %>%
      mutate(
        content_tiles = number( .data[[fill_col]], accuracy = 0.1) 
      )


  }
  

  
  
  plot <- ggplot(plot_data,
      aes(
        x = prob_review,
        y = (entropy_factor - 1) ,
      ),
    ) +
    geom_tile_interactive(
      aes(
        fill = .data[[fill_col]],
        data_id = i
      ),
      color = 'white'
    ) +
    geom_text(
      aes(
        label = content_tiles
      ),
      color = "#FFFFFF",
    ) +
    theme_minimal() +
    theme(
      legend.position = "top"
    ) +
    labs(
      x = "% Review",
      y = "Entropy factor",
      fill = fill_name
    ) +
    scale_y_continuous(
      labels = scales::percent_format(accuracy = 0.01),
      breaks = dados_grafico$entropy_factor - 1,
      minor_breaks = NULL
    ) +
    scale_x_continuous(
      labels = scales::percent_format(accuracy = 1),
      breaks = dados_grafico$prob_review,
      minor_breaks = NULL
    ) +
    fill_scale_layer
 
  
  if(selectable){
    girafe(ggobj = plot, width_svg = 10, height_svg = 10, options = list(opts_selection(selected = "1", type = "single", css = "fill:blue") ))
  }else{
    girafe(ggobj = plot, width_svg = 10, height_svg = 10)
  }
  
}


girafeOutput(
    outputId = "all_eqs"
)


output$all_eqs <- renderGirafe( create_plot( data = dados_grafico ))


```




```{r}


create_plot(data = company_payoff, fill_col = "total_merges", fill_name = "total_merges", selectable = FALSE)


```




```{r}


results_filtrado <- reactive({
  
  results %>% 
    filter(
      i == input$all_eqs_selected
    )
  
})





girafeOutput(
    outputId = "eq"
)

output$eq <- ggiraph::renderGirafe({
  

  plot <- results_filtrado() %>% 
    mutate(
      across(
        .cols = starts_with("complete_"),
        .fns = ~str_sub(.x, start = 1, end =  1)
      )
    ) %>% 
    group_by(complete_strategy_2, complete_strategy_3) %>% 
    mutate(
      best_1 = if_else(merges_1 == max(merges_1), "orange", "darkgray")
    ) %>%
    ungroup() %>% 
    group_by(complete_strategy_1, complete_strategy_3) %>% 
    mutate(
      best_2 = if_else(merges_2 == max(merges_2), "orange", "darkgray")
    ) %>%
    ungroup() %>% 
    group_by(complete_strategy_1, complete_strategy_2) %>% 
    mutate(
      best_3 = if_else(merges_3 == max(merges_3), "orange", "darkgray")
    ) %>%
    ungroup() %>% 
    ggplot() +
    geom_tile(
        aes(
          x = complete_strategy_1,
          y = complete_strategy_2,
          fill = best_1 == "orange" & best_2 == "orange" & best_3 == "orange"
        ),
        show.legend = FALSE,
        alpha = 0.3,
        color = "black"
    ) +
    geom_text(
      aes(
        x = complete_strategy_1,
        y = complete_strategy_2,
        label = number(merges_1, accuracy = 0.1),
        color = best_1
      ),
      nudge_x = -0.3
    ) +
    geom_text(
      aes(
        x = complete_strategy_1,
        y = complete_strategy_2,
        label = number(merges_2, accuracy = 0.1),
        color = best_2
      ),
    ) +
    geom_text(
      aes(
        x = complete_strategy_1,
        y = complete_strategy_2,
        label = number(merges_3, accuracy = 0.1),
        color = best_3
      ),
      nudge_x = .3
    ) +
    scale_color_identity() +
    scale_fill_manual(
      values = c("white", "yellow")
    ) +
    facet_row(
      facets = vars(complete_strategy_3),
      labeller = label_both
    ) +
    theme_minimal()
  
    girafe(ggobj = plot, width_svg = 10, height_svg = 10 )

  
}



)


```







